# Generated by Django 5.0.3 on 2024-04-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_sessionyearmodel_remove_students_session_end_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='barcode_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Staff'), (3, 'Student')], default=1, max_length=10),
        ),
    ]
