# Generated by Django 5.0.3 on 2024-05-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_customuser_barcode_number_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sessionyearmodel',
            managers=[
            ],
        ),
    ]
